package lombardabi

var LOMBARD_CLAIM_ABI string = `[
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_merkleRoot",
            "type":"bytes32"
         },
         {
            "internalType":"address",
            "name":"_token",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_owner",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"_claimEnd",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_vault",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_pauser",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_approver",
            "type":"address"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"target",
            "type":"address"
         }
      ],
      "name":"AddressEmptyCode",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"AddressInsufficientBalance",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"AlreadyClaimed",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ClaimFinished",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ClaimNotFinished",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ClaimWithProofNotEnabled",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"EmptyMerkleProof",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"EnforcedPause",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ExpectedPause",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"FailedInnerCall",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidAmount",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidMerkleProof",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidMerkleRoot",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidProof",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"InvalidToken",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"OnlyRecipientCanStake",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"owner",
            "type":"address"
         }
      ],
      "name":"OwnableInvalidOwner",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"OwnableUnauthorizedAccount",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"ReentrancyGuardReentrantCall",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"token",
            "type":"address"
         }
      ],
      "name":"SafeERC20FailedOperation",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"StakingNotEnabled",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"Unauthorized",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"WrongAddress",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"WrongClaimEnd",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"WrongStakeAmount",
      "type":"error"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"oldApprover",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newApprover",
            "type":"address"
         }
      ],
      "name":"ApproverChanged",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"Claimed",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"user",
            "type":"bytes32"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"address",
            "name":"dstAddress",
            "type":"address"
         }
      ],
      "name":"ClaimedWithProof",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"previousOwner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferStarted",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"previousOwner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferred",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"Paused",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"oldPauser",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newPauser",
            "type":"address"
         }
      ],
      "name":"PauserChanged",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"account",
            "type":"address"
         }
      ],
      "name":"Unpaused",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"oldVault",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newVault",
            "type":"address"
         }
      ],
      "name":"VaultChanged",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"Withdrawn",
      "type":"event"
   },
   {
      "inputs":[
         
      ],
      "name":"CLAIM_END",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"MERKLE_ROOT",
      "outputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"TOKEN",
      "outputs":[
         {
            "internalType":"contract IERC20",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"acceptOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"approver",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_newApprover",
            "type":"address"
         }
      ],
      "name":"changeApprover",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newPauser",
            "type":"address"
         }
      ],
      "name":"changePauser",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_newVault",
            "type":"address"
         }
      ],
      "name":"changeVault",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_account",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"bytes32[]",
            "name":"_merkleProof",
            "type":"bytes32[]"
         }
      ],
      "name":"claim",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_account",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"bytes32[]",
            "name":"_merkleProof",
            "type":"bytes32[]"
         }
      ],
      "name":"claimAndStake",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_account",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"bytes32[]",
            "name":"_merkleProof",
            "type":"bytes32[]"
         },
         {
            "internalType":"uint256",
            "name":"_stakeAmount",
            "type":"uint256"
         }
      ],
      "name":"claimAndStake",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_account",
            "type":"bytes32"
         },
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_dstAddress",
            "type":"address"
         },
         {
            "internalType":"bytes32[]",
            "name":"_merkleProof",
            "type":"bytes32[]"
         },
         {
            "internalType":"uint256",
            "name":"_stakeAmount",
            "type":"uint256"
         },
         {
            "internalType":"bytes",
            "name":"_proof",
            "type":"bytes"
         }
      ],
      "name":"claimAndStakeWithProof",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"_account",
            "type":"bytes32"
         },
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_dstAddress",
            "type":"address"
         },
         {
            "internalType":"bytes32[]",
            "name":"_merkleProof",
            "type":"bytes32[]"
         },
         {
            "internalType":"bytes",
            "name":"_proof",
            "type":"bytes"
         }
      ],
      "name":"claimWithProof",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"user",
            "type":"address"
         }
      ],
      "name":"hasClaimed",
      "outputs":[
         {
            "internalType":"bool",
            "name":"claimed",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"user",
            "type":"bytes32"
         }
      ],
      "name":"hasClaimedByProof",
      "outputs":[
         {
            "internalType":"bool",
            "name":"claimed",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"pause",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"paused",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"pauser",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"pendingOwner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"renounceOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"transferOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"unpause",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"vault",
      "outputs":[
         {
            "internalType":"contract IERC4626",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"withdraw",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   }
]`
